### ISSUE TITLE
Atom Feed Support

### ISSUE THREAD

**Issue by ddkasa** [dhvcc/rss-parser#46]
`NotImplementedError: ATOM feed is not currently supported`

Is this currently being worked on?

I understand #1 was opened a while back, but is closed at the moment.

I can create a PR for this, but I am curious where this stands at the moment or if this repo is even active?

**Comment by dhvcc** [comment]
Hey, @ddkasa, yeah this is planned with to ETA. Implementation should be fairly simple, just adding the models for the standard as it was with rss

As for spec I'd grab go to https://validator.w3.org/feed/docs/atom.html
This will covert ATOM v1.0. Not sure if we want to support older versions like 0.3, since they were released in 2003 afaik

**Comment by dhvcc** [comment]
PRs are welcome, for sure. I'm currently on a vacation so I will be able to check out your PR, but next week I might be very busy
